name: build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Ubuntu Packages
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: sudo apt-get install -y libassimp-dev libglfw3-dev

    - name: Install Windows packages
      if: matrix.os == 'windows-latest'
      shell: bash
      uses: lukka/run-vcpkg@v7
      with:
        setupOnly: true
    - run: |
        $VCPKG_ROOT/vcpkg install assimp:x64-windows
        $VCPKG_ROOT/vcpkg install glfw3:x64-windows
        $VCPKG_ROOT/vcpkg install glm:x64-windows

    - name: Generate
      shell: bash
      run: cmake -B.build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      
    - name: Build
      shell: bash
      run: cmake --build .build/
